config/routes.rb
Rails.application.routes.draw do
  resources :stocks do
    member do
      patch :update_price
    end
  end

  devise_for :users
  root 'stocks#index'
  get 'home/about'
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user

  validates :ticker, presence: true, uniqueness: { scope: :user_id },
                     format: { without: /\s|\W|\d|\.\,;\:!?\(\)\[\]/ }

  validates :buy_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :investment, presence: true, numericality: { greater_than: :buy_price }

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  require 'open-uri'
  require 'json'

  # GET /stocks or /stocks.json
  def index
    # fetch the stock for the current user
    @stocks = current_user.stocks

    # fetch the total investment and total value for the current user
    total_investment = 0
    total_value = 0
    @stocks.each do |stock|
      total_investment += stock.investment
      total_value += stock.price * (stock.investment / stock.buy_price)
    end
    # set the instance variables
    @total_investment = total_investment
    @total_value = total_value

    # chart data
    @chart_data_total = {
      "Total_Cost" => total_investment,
      "Current_Value" => total_value,
    }

    @chart_data_each_stock = {}
    total_investment = 0

    @stocks.each do |stock|
      total_investment += stock.investment
    end

    @stocks.each do |stock|
      percentage = total_investment.zero? ? 0 : (stock.investment / total_investment) * 100
      formatted_percentage = ActionController::Base.helpers.number_to_percentage(percentage, precision: 0)
      @chart_data_each_stock[stock.ticker] = formatted_percentage
    end


  end

  # GET /stocks/1 or /stocks/1.json
  def show
    @stock = Stock.find(params[:id])
    ticker = @stock.ticker
    api_key = ENV['POLYGON_API_KEY']

    limit = 366 # max 5000, default 10
    @timespan = params[:timespan] || 'day' # day, week, month, quarter, year
    @window = params[:window] || 50 # could be 10, 20, 50, 100, 200 ema

    url = "https://api.polygon.io/v1/indicators/ema/#{ticker}?timespan=day&adjusted=true&window=#{@window}&series_type=close&order=desc&limit=#{limit}&apiKey=#{api_key}"
    response = URI.open(url).read
    data = JSON.parse(response)
    values = data["results"]["values"]

    if values.present?
      @timestamp = values.map do |value|
        Time.at(value["timestamp"]/1000).strftime("%Y-%m-%d")
      end

      @value = values.map do |value|
        value["value"].round(2)
      end
    else
      @timestamp = []
      @value = []
    end

  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)
    @stock.user_id = current_user.id

    respond_to do |format|
      if @stock.save
        api_key = ENV['POLYGON_API_KEY']
        # Fetch the ticker name and logo
        url = "https://api.polygon.io/v3/reference/tickers/#{@stock.ticker.upcase}?apiKey=#{api_key}"
        response = URI.open(url).read
        ticker_data = JSON.parse(response)
        @ticker_name = ticker_data["results"]["name"]

        if @ticker_logo.present?
          @ticker_logo = ticker_data["results"]["branding"]["logo_url"]+"?""apikey=#{api_key}"
        else
          @ticker_logo = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/No_Image_Available.jpg/480px-No_Image_Available.jpg"
        end

        # Fetch the latest stock quote after saving the stock record
        @stock_info = PolygonService.fetch_quote(@stock.ticker)

        # Check if the stock quote was fetched successfully
        if @stock_info[:price].present?
          # Convert the API date
          date_seconds= @stock_info[:date]/1000
          api_date = DateTime.strptime(date_seconds.to_s, '%s')
          share = @stock.investment / @stock.buy_price
          value = @stock_info[:price] * share
          profit = value - @stock.investment
          # Update the stock record with the fetched price
          @stock.update(price: @stock_info[:price], updated_at: api_date, share: share, value: value, profit: profit, name: @ticker_name, logo: @ticker_logo)
          format.html { redirect_to stocks_url, notice: "Stock was successfully created." }
          format.json { render :show, status: :created, location: @stock }
        else
          # Handle the case where the stock quote could not be fetched
          @stock.destroy
          format.html { render :new, status: :unprocessable_entity, alert: "Failed to fetch stock quote." }
          format.json { render json: { error: "Failed to fetch stock quote." }, status: :unprocessable_entity }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @stock.update(stock_params)
        api_key = ENV['POLYGON_API_KEY']
        # Fetch the ticker name and logo
        url = "https://api.polygon.io/v3/reference/tickers/#{@stock.ticker.upcase}?apiKey=#{api_key}"
        response = URI.open(url).read
        ticker_data = JSON.parse(response)
        @ticker_name = ticker_data["results"]["name"]
        @ticker_logo = ticker_data["results"]["branding"]["logo_url"]+"?""apikey=#{api_key}"
        # Fetch the latest stock quote after updating the stock record
        @stock_info = PolygonService.fetch_quote(@stock.ticker)

        # Check if the stock quote was fetched successfully
        if @stock_info[:price].present?
          # Convert the API date
          date_seconds= @stock_info[:date]/1000
          api_date = DateTime.strptime(date_seconds.to_s, '%s')
          share = @stock.investment / @stock.buy_price
          value = @stock_info[:price] * share
          profit = value - @stock.investment
          # Update the stock record
          @stock.update(price: @stock_info[:price], updated_at: api_date, share: share, value: value, profit: profit, name: @ticker_name, logo: @ticker_logo)
          format.html { redirect_to stocks_url, notice: "Stock was successfully updated." }
          format.json { render :show, status: :ok, location: @stock }
        else
          # Handle the case where the stock quote could not be fetched
          format.html { render :edit, status: :unprocessable_entity, alert: "Failed to fetch updated stock quote." }
          format.json { render json: { error: "Failed to fetch updated stock quote." }, status: :unprocessable_entity }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end

  end

  def update_price
    # Fetch the latest stock quote after updating the stock record
    @stock = Stock.find(params[:id])
    @stock_info = PolygonService.fetch_quote(@stock.ticker)
  # Check if the stock quote was fetched successfully
    if @stock_info[:price].present?
      # Update the stock and date record with the fetched price
      date_seconds= @stock_info[:date]/1000
      api_date = DateTime.strptime(date_seconds.to_s, '%s')
      @stock.update(price: @stock_info[:price], updated_at: api_date)
      redirect_to stocks_path, notice: 'Stock price was successfully updated.'
    else
      # Handle the case where the stock quote could not be fetched
      redirect_to stocks_path, alert: 'Failed to fetch stock quote for price update.'
    end

  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy
    redirect_to stocks_path
  end

  def correct_user
    @stock = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not authorized to edit this stock" if @stock.nil?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :name, :price, :share, :buy_price, :investment, :updated_at, :value, :user_id, :logo)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<div class="col-md-6 offset-md-3">
  <div class="p-3 mb-2 bg-light text-dark">
    <h1><%= @stock.new_record? ? "New" : "Edit" %> Stock</h1>
    <%= simple_form_for(@stock) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :ticker %>
        <%= f.input :buy_price %>
        <%= f.input :investment %>
      </div>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>

  </div>
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/_stock.html.erb
<h1>I am a rendered show stock</h1>

app/views/stocks/edit.html.erb
<%= render "form", stock: @stock %>

app/views/stocks/index.html.erb
<h1 class="mt-4"> Portfolio</h1>
<div class="container mt-4">
  <div class="table-responsive">
    <table class="table table-hover table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th>Company</th>
          <th>Ticker</th>
          <th>Last Price</th>
          <th>Buy Price</th>
          <th>Cost</th>
          <th>Shares</th>
          <th>Value</th>
          <th>P/L</th>
          <th>Price Date</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @stocks.each do |stock| %>
          <% if stock.ticker.present? %>
            <% if stock.price.present? && stock.name.present? %>
              <tr>
                <td><%= stock.name %></td>
                <td><%= link_to stock.ticker.upcase, stock_path(stock) %></td>
                <td><%= number_to_currency(stock.price) %></td>
                <td><%= number_to_currency(stock.buy_price) %></td>
                <td><%= number_to_currency(stock.investment) %></td>
                <td><%= number_to_human(stock.share) %></td>
                <td><%= number_to_currency(stock.value) %></td>
                <% if stock.profit > 0 %>
                  <td class="text-success"><%= number_to_currency(stock.profit) %></td>
                <% elsif stock.profit < 0 %>
                  <td class="text-danger"><%= number_to_currency(stock.profit) %></td>
                <% else %>
                  <td><%= number_to_currency(stock.profit) %></td>
                <% end %>
                <td><%= stock.updated_at.strftime("%d/%m/%Y %H:%M") %></td>
                <td>
                  <center>

                    <%= link_to(edit_stock_path(stock), class: "btn btn-outline-secondary") do %>
                      <i class="fas fa-pen-to-square"></i>
                    <% end %>

                    <%= link_to(stock_path(stock), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger") do %>
                      <i class="fas fa-trash-alt"></i>
                    <% end %>

                    <%= link_to(update_price_stock_path(stock), data:{turbo_method: :patch, turbo_confirm: 'Are you sure?'} , class: "btn btn-outline-primary") do %>
                      <i class="fas fa-sync-alt"></i>
                    <% end %>
                  </center>
                </td>
              </tr>
            <% else %>
              <p>Invalid ticker!<%= link_to(edit_stock_path(stock), class: "btn btn-outline-secondary") do %>
                                <i class="fas fa-pen-to-square"></i>
                                <% end %>
              </p>
            <% end %>
          <% elsif @stock_info[:error].present? %>
            <p>Error: <%= @stock_info[:error] %></p>
          <% elsif @stock_info[:empty].present? %>
            <p><%= @stock_info[:empty] %></p>
          <% end %>
        <% end %>

        <% if @stocks.count > 0 %>
          <!-- Total row -->
          <tr>
            <td colspan="4"><strong>Total</strong></td>
            <td><%= number_to_currency(@total_investment) %></td>
            <td></td> <!-- If you don't have a 'Shares' column for total -->
            <td><%= number_to_currency(@total_value) %></td>
            <td colspan="4"></td> <!-- If you don't have a 'Profit/Loss' column for total -->
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <% if @stocks.count > 0 %>
    <!-- Display only when there's stock added-->
    <div class="row mt-4 border rounded">
      <div class="col-md-6 mb-4">
        <!-- Chart 1: Total -->
        <%= column_chart @chart_data_total, stacked: true, width: "100%", height: "200px" %>
      </div>
      <div class="col-md-6">
        <!-- Chart 2: Each Stock -->
        <%= pie_chart @chart_data_each_stock, width: "100%", height: '200px', library: { title: 'Stock Values' } %>
      </div>
    </div>
  <% end %>
</div>

app/views/stocks/new.html.erb
<%= render "form", stock: @stock %>

app/views/stocks/show.html.erb
<div data-controller="chart-form">
  
  <div class="header-container">
    <small><%= @stock.name %></small>
    <hr>
    <h1 class="m-0">
      $<%= @stock.price %>
    </h1>
  </div>
    <% timespan = @timespan =="day" ? "Daily" : @timespan.upcase + "LY" %>
    <% window = @window %>

    <%= line_chart @timestamp.zip(@value).to_h, height: '500px', xtitle: '', ytitle: 'Price', library: { hAxis: { title: 'TimeStamp' }, vAxis: { title: 'Value' } } %>
    <p class="text-center"><%= "#{timespan} #{window}EMA" %></p>
  </div>
  <div class="chart-and-form-container">
    <div class="form-container">
      <%= form_with(url: stock_path(@stock), method: :get, id: 'chart-form') do |f| %>
        <div class="form-inputs">
          <div class="form-group inline-form-element">
            <%= f.label :timespan %>
            <%= f.select :timespan, ['day', 'week', 'month', 'quarter', 'year'], {}, data: { chart_form_target: 'timespan' } %>
          </div>

          <div class="form-group inline-form-element">
            <%= f.label :window %>
            <%= f.select :window, [10, 20, 50, 100, 200], {}, data: { chart_form_target: 'window' }%>
          </div>

          <div class="form-group inline-form-element">
            <%= f.submit "Update", class: "btn btn-primary btn-sm p-0" %>
        </div>
      <% end %>
    </div>
  </div>
</div>