config/routes.rb
Rails.application.routes.draw do
  resources :stocks do
    member do
      patch :update_price
    end
  end

  devise_for :users
  root 'stocks#index'
  get 'home/about'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def about
    # @stock_info = PolygonService.fetch_quote(params[:ticker])
  end

  def index
    # @stock_info = StockQuoteService.fetch_quote(params[:ticker])
    # @stock_info = PolygonService.fetch_quote(params[:ticker])
  end



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flash.html.erb
<br>
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= content_tag(:div, sanitize(msg)) %>
  </div>
<% end %>

app/views/home/_footer.html.erb
<footer>
  <center>

    <small>
      &copy;
      ErwinAdorable
      <%= Time.now.year %>

    </small>
  </center>
</footer>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "StockPortfolio", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", home_about_path, class: "nav-link" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Portfolio", stocks_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Add Stock", new_stock_path, class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
 <header>
    <h1>About Us</h1>
  </header>

  <section>
    <h2>Welcome to our Stock Portfolio App!</h2>
    <p>
      Our Stock Portfolio App is designed to help you manage and track your stock investments effectively. Whether you are a seasoned investor or just getting started, our app provides a user-friendly interface to keep you informed about your portfolio's performance.
    </p>

    <h3>Key Features:</h3>
    <ul>
      <li>Track your stock holdings</li>
      <li>View real-time stock prices</li>
      <li>Analyze historical performance</li>
      <!-- Add more features as needed -->
    </ul>

    <h3>Our Mission:</h3>
    <p>
      We are committed to empowering individuals in making informed investment decisions. Our mission is to provide a reliable and user-friendly platform for managing stock portfolios, helping users achieve their financial goals.
    </p>

    <h3>Contact Us:</h3>
    <p>
      Have questions or feedback? Feel free to reach out to us at <a href="mailto:adorable.erwin@gmail.com">adorable.erwin@gmail.com</a>.
    </p>
  </section>

app/views/home/index.html.erb
<%= form_with(url: root_path, method: :get) do |form| %>
    <%= form.label :ticker, 'Stock Ticker:' %>
    <%= form.text_field :ticker, placeholder: "Enter stock ticker" %>
    <%= form.submit 'Lookup' %>
<% end %>